#!/usr/bin/env python

"""
specific local python paths
#!/usr/local/bin/python
#!/Users/lokeshsoni/miniconda3/bin/python

generic python path
#!/usr/bin/env python
"""

from argparse import ArgumentParser


# 1 get the parser
parser = ArgumentParser(
    description="Greeting utility"
)

# 2 give arguments
parser.add_argument(
    "--name",
    type=str,
    help="Name of the user",
    required=True
    # default="admin"
)

parser.add_argument(
    "--role",
    type=str,
    help="Role of the user",
    required=True
    # default="bench"
)


# 3 parse the arguments
args = parser.parse_args()
# print(args)

name = args.name
role = args.role

if name and role:
    print(f"Hello {name}, welcome to the {role} team!")
else:
    print("need name and role values")


_ = """
r - read
w - write
x - execute

ft  u    g    o
--  --   --   --
d   rwx  r-x  r-x  
-   rw-  r--  r--  greet.py
-   rwx  r-x  r-x  tmp.txt

/greet.py --name firoz --role dba
/greet.py --help

mv greet.py greet

greet --name firoz --role dba

copy script
cp greet /bin/
use sudo when permission denied

create a link/shortcut
ln -s src dest/name

greet --name firoz --role dba
"""
